name: master

on: [ push ]
env:
  # BASIC_PACKAGES is used fo the basic tools (make)
  BASIC_PACKAGES: git build-essential ccache libgc-dev graphviz libunwind-dev libreadline-dev pkg-config
  # MORE_PACKAGES is used for more tools and libs (make more)
  MORE_PACKAGES: libgmp-dev libcurl4-openssl-dev libevent-dev openjdk-17-jdk-headless libgles-dev libegl-dev libsdl1.2-dev libsdl2-dev libsdl2-mixer-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-net-dev libsdl2-ttf-dev libgtk-3-dev inkscape postgresql libxdg-basedir-dev gettext libsqlite3-dev libpq-dev libmongoc-dev openmpi-bin libopenmpi-dev rename

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y $BASIC_PACKAGES $MORE_PACKAGES
    - uses: actions/checkout@v4
    - run: make
    - uses: actions/upload-artifact@v4
      with:
        path: bin
        name: bin
    - run: make catalog
    - uses: actions/upload-artifact@v4
      with:
        path: catalog.out/
        name: catalog
    - run: make docs
    - uses: actions/upload-artifact@v4
      with:
        path: doc
        name: doc
    - run: make web -C share/man
    - uses: actions/upload-artifact@v4
      with:
        path: share/man/www
        name: man
